// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB41m2Rm3aK_7mugaQpsueHejbb-5Isf3Q',
    appId: '1:598205660262:android:22b0cb1708bdef780381a7',
    messagingSenderId: '598205660262',
    projectId: 'kin-experience',
    storageBucket: 'kin-experience.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCMnB1dLiGMA7Uk62hb-JRX1jmRwnHcy8',
    appId: '1:598205660262:ios:54cc3fda0d9e5f230381a7',
    messagingSenderId: '598205660262',
    projectId: 'kin-experience',
    storageBucket: 'kin-experience.firebasestorage.app',
    iosBundleId: 'com.kin.experience',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1PnsvmAvrVasQhIU-gDFPNxiSveUJ6kI',
    appId: '1:598205660262:web:acd26a4546d498130381a7',
    messagingSenderId: '598205660262',
    projectId: 'kin-experience',
    authDomain: 'kin-experience.firebaseapp.com',
    storageBucket: 'kin-experience.firebasestorage.app',
    measurementId: 'G-133MGBPREK',
  );

}